export const emptyContentBlockAnim = {
  contentBlock: {},
  preContent: {},
  preHeading: {},
  info: {},
  infoTag: {},
  infoTags: {},
  headingTitle: {},
  subTitle: {},
  bodyCopy: {},
  primaryCta: {},
  secondaryCta: {},
  media: {},
  backgroundMedia: {},
  buttonGroup: {},
};
